// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrktdM47mPNcB2JEDuzTlra79Iv5YP_g',
    appId: '1:509317486900:android:dfbe2dd28aee94ced6ed61',
    messagingSenderId: '509317486900',
    projectId: 'leawin-apo',
    databaseURL: 'https://leawin-apo.firebaseio.com',
    storageBucket: 'leawin-apo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASz9HzCkZZAeBv2PeBKFctzINp3Swvdtg',
    appId: '1:509317486900:ios:77b7fd6e1a3d0207d6ed61',
    messagingSenderId: '509317486900',
    projectId: 'leawin-apo',
    databaseURL: 'https://leawin-apo.firebaseio.com',
    storageBucket: 'leawin-apo.firebasestorage.app',
    androidClientId: '509317486900-1m2h0m919eq1cehrh478370lesmi3r7u.apps.googleusercontent.com',
    iosClientId: '509317486900-8648bb8p0b1k47cup1t7cgl1amkgh7i5.apps.googleusercontent.com',
    iosBundleId: 'com.app.learnandwinapp',
  );

}